// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kygtggwqfgnsbylkuqrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5Z3RnZ3dxZmduc2J5bGt1cXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzI0MjEsImV4cCI6MjA2NzA0ODQyMX0.OtFSgSgFAsfG0I5cf8YHxKO8MXL54JjgPg-F60K_od8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});